# Generated by Django 4.1.6 on 2023-03-09 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='id',
        ),
        migrations.AlterField(
            model_name='answers',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='posts.question'),
        ),
    ]
