# Generated by Django 4.1.7 on 2023-03-14 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255, null=True)),
                ('Body', models.TextField(max_length=255)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
                ('Date_Edited', models.DateTimeField(auto_now=True)),
                ('Correct_Code_Field', models.TextField(blank=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
            ],
        ),
    ]
