# Generated by Django 4.1.6 on 2023-03-09 11:46

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_answers_id_alter_answers_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='post',
            field=models.OneToOneField(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='posts.question'),
        ),
    ]
