# Generated by Django 4.1.6 on 2023-03-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_answers_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
    ]
