# Generated by Django 4.1.7 on 2023-03-17 19:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
                ('Date_Edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upvotes_comments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
                ('Date_Edited', models.DateTimeField(auto_now=True)),
                ('voted_ob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.comments')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='DownVoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='Upvoted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Downvote_comments',
            fields=[
                ('upvotes_comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.upvotes_comments')),
            ],
            bases=('posts.upvotes_comments',),
        ),
        migrations.CreateModel(
            name='DownVotes',
            fields=[
                ('upvotes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.upvotes')),
            ],
            bases=('posts.upvotes',),
        ),
        migrations.AddField(
            model_name='upvotes',
            name='voted_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
        ),
    ]
